### ISSUE TITLE
free_energy_clustering.visualize not working

### ISSUE THREAD

**Issue by DSilva27** [anniewesterlund/Tutorial_FE_clustering#3]
Hi, I tried to follow the tutorial but I got an error when using the visualization function. 

`NameError: name 'copy' is not defined`

I fixed it by importing `copy` in `free_energy_clustering/GMM_free_energy.py`

**Comment by anniewesterlund** [comment]
Thank you for letting me know! I fixed the import now in the repo as well. Let me know if you find any other problems.
